### PR TITLE
Fix for scroll bug

### LINKED ISSUE #19: Scroll bug
When you scroll in the mod's pop-up window, a single 'tick' of the scroll wheel takes you all the way from the top to the bottom and vice versa.

### PR DESCRIPTION
**Pull request by Codenade**
Closes #19

### CODE REVIEW

**Comment by Aviage-01** [comment]
Do I need to reinstall the mod through CKAN to get this update, or should it happen automatically?
image

**Comment by Codenade** [comment]
@Aviage-01 I have not yet put this feature into the experimental version. I want to merge #25 and #26 before that.

> Do I need to reinstall the mod through CKAN to get this update, or should it happen automatically?

You will probably have to reinstall because it checks for a newer version and only then gives you the option to update.

**Comment by Aviage-01** [comment]
Gotcha. Please do let me know when that's released!

**Comment by Codenade** [comment]
Hey, @Aviage-01 the experimental release is now ready. The axes binding fix as well as the camera zoom fix are now included.
#### Known issues
* loading of CameraZoom does not work

**Comment by Aviage-01** [comment]
Alright! I'll go and back up input.json, then reinstall from the same .ckan file!

**Comment by Aviage-01** [comment]
I reinstalled the mod, including purging the cache of CKAN, but it's still the same version of the mod, without the bug-fixes. Is there something I'm doing wrong, or did the versions get merged incorrectly?

**Comment by Codenade** [comment]
I had to first uninstall using ckan then purge the cache and then install from the .ckan and it worked. You can also try changing the version field in the .ckan file to something unique. Of course you can still install manually too. The size of ksp2-inputbinder.dll should be 57856 Bytes with an

**Comment by Codenade** [comment]
I had to first uninstall using ckan then purge the cache and then install from the `.ckan` and it worked. You can also try changing the version field in the `.ckan` file to something unique. Of course you can still install manually too. The size of `ksp2-inputbinder.dll` should be `57856 Bytes` with a SHA1 hash of `408133db2e47fa5e39001dd396e16a6f96d26b8c` if thats something need.

**Comment by Aviage-01** [comment]
I can't find which .zip file I'm supposed to download to install manually? The one from Spacedock is out of date, and I couldn't see one on github.

I'm very sorry I've been unable to figure this out.

**Comment by Aviage-01** [comment]
Scratch that! I figured it out!

**Pull request merged**
