### PR TITLE
new loading system, processors displayed on main screen, slider scale adjustment, ui fixes, reset functionality, ...

### LINKED ISSUE #20: Bug in adding additional control fields
I am attempting to set the ability to zoom the camera in and out from my joystick during flight, so I placed 'Flight.activeCameraZoom' in the game_actions_to_add.txt file, and rebooted the game, but no option is appearing for it in the in-game mod GUI.
image

### PR DESCRIPTION
**Pull request by Codenade**
* moved `input.json` from `BepInEx/plugins/inputbinder` to `BepInEx/config/inputbinder/profiles`
* `Flight.CameraZoom`, `MapView.HideMap` and `Global.QuickLoad` are now available by default
* refactored loading system (loading of old files should still work but is not guaranteed to always yield the same bindings as before)
* actions with expected control type Vector2 (e.x. Flight.CameraZoom) can now be assigned to
* slider range can now be changed by editing `BepInEx/config/inputbinder/inputbinder.cfg`
* slider range is now [-2;2] by default
* processors are now displayed inside the main page of the app instead of only when clicking the associated button
* renamed button "Change" to "Rebind" and "Modifiers" to "Processors" to better match the terminology used in Unity's InputSystem
* new "Reset All" button in the window header to remove overrides from all bindings, clicking this button will open a dialog asking for confirmation
* removed "Remove all gamepad bindings" button
* clearing a binding now sets its overridePath to "" instead of "none"
* fixed boolean processor arguments not displaying their name properly
* fixed UI creating invisible copies
* fixed processors list empty when trying to add one to an action with an expected control type of Button

### CODE REVIEW

**Comment by Aviage-01** [comment]
What does it mean for CameraZoom to be a 2d axis?

**Comment by Aviage-01** [comment]
Also, and this is a very minor thing, but it might be nice if camera zoom was in the list next to camera pitch and camera yaw, just bundling everything together.

**Comment by Codenade** [comment]
> What does it mean for CameraZoom to be a 2d axis?

I have no idea why the devs opted to use a 2d axis for zooming the camera but basically that means that you cannot assign normal axis directly so I made another composite binding allowing you to bind x and y axes individually.
Here's some documentation regarding the InputSystem:
https://docs.unity3d.com/Packages/com.unity.inputsystem@1.5/manual/Controls.html#control-types
https://docs.unity3d.com/Packages/com.unity.inputsystem@1.5/manual/ActionBindings.html#composite-bindings

> Also, and this is a very minor thing, but it might be nice if camera zoom was in the list next to camera pitch and camera yaw, just bundling everything together.

It should be if you havent saved it yet and are not adding it via game_actions_to_add.txt

**Comment by Codenade** [comment]
@Aviage-01 saving and loading should now work. I have reworked how the mod handles saving and loading. It should still be able to load the old configuration.

I have also changed the range of the slider for #24 to [-2;+2].

I replaced the experimental version on the [GitHub releases page](https://github.com/Codenade/ksp2-inputbinder/releases/tag/experimental) with this one.

**Comment by Aviage-01** [comment]
Alright, thanks! I'll go and test that all out

**Comment by Aviage-01** [comment]
Works great! Can't find any bugs! I'll keep playing with it, to see if any other problems arise.

**Pull request merged**
